# Generated by Django 4.2.7 on 2024-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img',
            field=models.ImageField(default=1, upload_to='topic_img/'),
            preserve_default=False,
        ),
    ]
