# Generated by Django 4.2.7 on 2024-01-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='img',
        ),
        migrations.AddField(
            model_name='entry',
            name='topic_Img',
            field=models.ImageField(default=1, upload_to='topic_images/'),
            preserve_default=False,
        ),
    ]
